services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./Chinook_PostgreSql.sql:/docker-entrypoint-initdb.d/init.sql
